package io.github.ivarm1984.bot;

import io.github.ivarm1984.engine.GameState;
import io.github.ivarm1984.engine.Move;
import io.github.ivarm1984.engine.PieceColor;

import java.util.List;

/**
 * Everything a bot receives to make one decision. Legal moves are always
 * pre-generated by the engine and never empty (the match runner only calls a
 * bot when it is that bot's turn to move) - a bot's job is purely to choose
 * among {@code legalMoves}, never to re-derive them.
 */
public record BotInput(
        GameState state,
        PieceColor myColor,
        List<Move> legalMoves,
        List<Move> moveHistory,
        Deadline deadline
) {
}
